### ISSUE TITLE
measure unable to create dashboard due to database connectivity

### ISSUE THREAD

**Issue by rashamalek** [MeasureOSS/Measure#109]
Hi,
I would like to ask for advise regarding Measure deoployment, 

Our goal would be to run Measure against our internal Github Enterprise, and get insights over the pull requests and and people collaboration.

Unfortunately it is not possible as it requires multiple code changes as currently Github API url is hardcoded in its submodules like ghcrawler* .

So We decided to run it as a Poc and configure it against our Github.com organizations.

Unfortunately the documentation is not sufficient, and in some parts not clear at all.

1. For example in Initial setup part it makes a webserver with PHP5.5+ as a requirement, 
and talks about a /path/to/Measure/database and dashboard.
but it is not clear where these paths are, are they the . folder when you clone https://github.com/MeasureOSS/Measure or somewhere else?

2. Next it talks about checking out ghcrawler and -cli, but in the next line it also clones 'git clone https://github.com/Microsoft/ghcrawler-dashboard.git' but at least it never uses it again.

3. also running the latest part "node markdash.js" produces the following warning as follow
Problem message:
  WARNING: there seem to be no database entries for some of your
  repositories. You may need to wait a little longer for the data
  to arrive before these dashboards can be generated.
  Alternatively, you may need to tell the crawler to fetch these
  data. Run the following commands in the ghcrawler-cli folder:
  node bin/cc orgs xxxxx
  node bin/cc queue xxxxx/yyyyy
  xxxxx/yyyyy
  node bin/cc start 10

It seems that It cannot retrieve data from the database although I am able to access mongodb which is running in docker , and it contains data:

```
docker ps --no-trunc
CONTAINER ID                                                       IMAGE                            COMMAND                                  CREATED             STATUS              PORTS                                                                       NAMES
a4a2fe7d5b97fc6151cc3748653cf8cdbc7d0540b65232d19eed984a18088243   boxedcode/alpine-nginx-php-fpm   "/entrypoint.sh"                         3 hours ago         Up 3 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                    nginx-measure
fa25c45f52873d3d5b6678ef4a953244f3157e0941ddc920cb63e2218f6d9e16   docker_dashboard                 "docker-entrypoint.sh npm start"         5 hours ago         Up 5 hours          127.0.0.1:4000->4000/tcp, 5858/tcp                                          docker_dashboard_1
a9b4de5ae7edb4dffb0694fc5a1ac04f0dca882016c78eb40770e1520f6be4b3   docker_crawler                   "docker-entrypoint.sh npm start"         5 hours ago         Up 5 hours          0.0.0.0:3000->3000/tcp, 5858/tcp                                            docker_crawler_1
0c0b6da68d4040ed9e9ec46dbe479a6fc2c629e27667dc72754cdc68e95c16b3   metabase/metabase:latest         "/app/run_metabase.sh"                   5 hours ago         Up 5 hours          127.0.0.1:5000->3000/tcp                                                    docker_metabase_1
4a183a4e5ca1fa8e24a001ee0f81dfc376df03a091092943ab04a4ac06e4188a   mongo:latest                     "docker-entrypoint.sh mongod"            5 hours ago         Up 5 hours          127.0.0.1:27017->27017/tcp                                                  docker_mongo_1
9354111f60d8186aca22f3507c5e7aa153b9042457c4a6591359f40f1776a3ce   rabbitmq:management              "docker-entrypoint.sh rabbitmq-server"   5 hours ago         Up 5 hours          4369/tcp, 5671-5672/tcp, 15671/tcp, 25672/tcp, 127.0.0.1:15672->15672/tcp   docker_rabbitmq_1
9000bda88252bd6d99d80f02bffb70533ef0a7929459a7d6334ac044a9de4c80   redis:latest                     "docker-entrypoint.sh redis-server"      5 hours ago         Up 5 hours          6379/tcp                                                                    docker_redis_1
```

Could you please advise how to fix this?

**Comment by stuartlangridge** [comment]
1. The database and dashboard paths are where Measure stores its output -- HTML, CSS, and JavaScript files for the dashboard, and a SQLite database for the database. Where you'd like those to be output is up to you; you can set those paths to wherever you want in the config file and Measure will put them there. (I'll look at explaining this more clearly in the instructions.)
2. We do indeed suggest cloning ghcrawler-dashboard but don't use it. It is a web tool to monitor what the crawler is doing, for advanced users. I may remove that from the instructions, since most users don't need it; good tip.
3. Measure runs in two parts: the crawler fetches details of your repositories from github's API and stores them in MongoDB, and then makedash analyses the data in MongoDB to actually create the Measure dashboards. The problem message there is saying that it can't find the data it needs in MongoDB for some of your repositories; this normally means that ghcrawler hasn't fetched it all, yet. After running the crawler, you need to teach it which repositories to fetch data for; that's the list of commands that the problem message tells you to run. After you run those commands, it will take some time before all the data is fetched into MongoDB; that's what the problem message is warning you about. So, run all those commands in the ghcrawler-cli folder as the message suggests (which you may have already done), and then wait some time before running makedash and the message should have gone away. Especially the first time you fetch data, it does take a long time; there is a lot of information about your repositories to be fetched, and the Github API rate-limits how fast the crawler can fetch it.

**Comment by rashamalek** [comment]
Thanks @stuartlangridge for the extensive information;
After waiting for around 36 hours the first issue was resolved;
Second issue was the same as #99 ; changing mongo version to `image: mongo:3.4.16` in [ghcrawler/docker/common-services.yml](https://github.com/microsoft/ghcrawler/blob/master/docker/common-services.yml#L33) fixed the issue;
Currently `node makedash.js` is running and probably will take some time.
For now I will close the issue, and reopen alter in case needed.

Thanks
