### ISSUE TITLE
Closed PRs Widget

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#31]
should break out accepted vs rejected

**Comment by stuartlangridge** [comment]
Would it be acceptable here to add this to the existing "PRs opened and closed this month" stack graph, so instead of "opened PRs" and "closed PRs" bars we have "opened PRs", "closed accepted PRs" and "closed rejected PRs"?

![image](https://user-images.githubusercontent.com/4356350/33233986-08cfc5ee-d217-11e7-9acf-e1a44c834b82.png)

**Comment by irabinovitch** [comment]
That seems reasonable to me. @jeremy-lq are we sure "rejected" is the right word? Many PRs have their commits cherry picked into new PRs for example.

**Comment by jeremy-lq** [comment]
@irabinovitch, I don't believe the current GitHub API makes that easily trackable. It's possible I've missed it though. What would the alternative wording be?

**Comment by stuartlangridge** [comment]
I added a new widget for #30. Does that obviate the need for this, or does this issue document a need that the other graph doesn't cover?

![image](https://user-images.githubusercontent.com/4356350/33239704-52a23322-d29f-11e7-8de4-9d27bcdaaa56.png)

**Comment by jeremy-lq** [comment]
Closing this. Can revisit Ilan's suggestion if we find a reasonable way to extract the data.
